---
version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=user
    ports:
      - "7780:5432"
    volumes:
      - db:/var/lib/postgresql/data
  redis:
    image: redis:5.0-alpine
    ports:
      - 6381:6379
      - 32768:32768
    volumes:
      - redis:/data
volumes:
  redis:
    driver: local
  db:
